# nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]
aptPkgs = ["python3", "build-essential"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"