# Railway Configuration for Sourdough Pete

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[networking]
serviceDomain = "sourdough-pete.railway.app"