# Railway Configuration for Carmen Sandiego

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 10
healthcheckStartPeriod = 60
restartPolicyType = "always"
startCommand = "npm start"

[environment]
NODE_ENV = "production"

[networking]
serviceDomain = "glennallencarmansandiego-production.railway.app"