# Railway Configuration for Carmen Sandiego

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_VERSION = "20.19.0"

[networking]
serviceDomain = "glennallencarmansandiego-production.railway.app"