# Railway Configuration for Carmen Sandiego

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"

[networking]
serviceDomain = "glennallencarmansandiego-production.railway.app"